name: CD - Terraform Deploy (OIDC)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "infra/**"
      - "src/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12 for Layer Build
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Lambda Layer Dependencies
        run: |
          mkdir -p ../build/layer/python
          pip install -t ../build/layer/python --platform manylinux2014_x86_64 --only-binary=:all: --python-version 3.12 --implementation cp "pydantic>=2.7.0" "aws-lambda-powertools[all]>=3.0.0"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Configure AWS Credentials via GitHub OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::293162038789:role/serverless-orders-github-oidc-prod
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply (Main Branch Only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
